language: android
before_install:
  # Download required maven android sdk jar (i.e. see the 'provided' google:google.jar in pom.xml)
  - cd ..
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer/platforms
  - mvn install -P4.4
  - cd $TRAVIS_BUILD_DIR
before_script: "mvn validate"
android:
  components:
    - build-tools-23.0.3
    - android-19
